spring:
  application:
    name: cs16-matchmakingspring
  datasource:
    url: ${SPRING.DATASOURCE_URL:jdbc:postgresql://localhost:5433/cs16mt}
    username: ${SPRING.DATASOURCE_USERNAME:cs16mt}
    password: ${SPRING.DATASOURCE_PASSWORD:cs16mt}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  show-sql: true